import {meal, category} from '../models';
import Meal from '../models/menuModel';

export const CATEGORIES = [
  new category('c1', 'Bữa trưa', '#f5428d'),
  new category('c2', 'Thịt gà', '#f54242'),
  new category('c3', 'Cá', '#f5a442'),
  new category('c4', 'Bánh mì', '#f5d142'),
  new category('c5', 'Món ăn cho trẻ em', '#368dff'),
  new category('c6', 'Món ăn cho mẹ', '#41d95d'),
  new category('c7', 'Kho', '#9eecff'),
  new category('c8', 'Thịt gà', '#b9ffb0'),
  new category('c9', 'Tăng năng lượng', '#ffc7ff'),
  new category('c10', 'Bữa tối', '#47fced'),
  new category('c11', 'Món nhậu', '#9eecff'),
  new category('c12', 'Gỏi', '#b9ffb0'),
  new category('c13', 'Om', '#ffc7ff'),
  new category('c14', 'Thịt khác', '#47fced'),
];
export const MEALS = [

  {
    id: 'm1',
    title: 'Bún chả',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 2,
    description:
      'Bún chả là một món ăn truyền thống của Việt Nam, bao gồm thịt nướng và bún tương đối dày.',
    ingredients: [
      {name: 'Thịt heo', amount: '200g'},
      {name: 'Bún', amount: '200g'},
      {name: 'Rau sống', amount: '200g'},
      {name: 'Nước mắm', amount: '2 muỗng canh'},
    ],
    spice: ['Tỏi', 'Ớt', 'Tiêu'],
    process:
      'Sơ chế thịt heo, nướng thịt, chế biến nước mắm, nấu bún, chuẩn bị rau sống.',
    perform:
      'Đặt bún, rau sống và thịt nướng trong tô, chấm nước mắm trước khi ăn.',
    use: 'Dùng bún chả khi còn nóng.',
    tips: 'Nên chọn thịt heo tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[0],
  },
  {
    id: 'm2',
    title: 'Phở bò',
    linkImage:
      'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 2,
    description:
      'Phở bò là một món ăn truyền thống của Việt Nam, bao gồm bò nướng và bún tương đối dày.',
    ingredients: [
      {name: 'Thịt bò', amount: '200g'},
      {name: 'Bún', amount: '200g'},
      {name: 'Rau sống', amount: '200g'},
      {name: 'Gia vị phở', amount: '2 muỗng canh'},
    ],
    spice: ['Hành', 'Ngò gai', 'Gừng'],
    process:
      'Sơ chế thịt bò, nướng thịt, chế biến gia vị phở, nấu bún, chuẩn bị rau sống.',
    perform:
      'Đặt bún, rau sống và thịt nướng trong tô, chấm gia vị phở trước khi ăn.',
    use: 'Dùng phở bò khi còn nóng.',
    tips: 'Nên chọn thịt bò tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[0],
  },
  {
    id: 'm3',
    title: 'Cơm gà',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 2,
    description: 'Cơm gà là một món ăn phổ biến, bao gồm gà nướng và cơm.',
    ingredients: [
      {name: 'Thịt gà', amount: '200g'},
      {name: 'Cơm', amount: '200g'},
      {name: 'Rau sống', amount: '200g'},
      {name: 'Nước mắm', amount: '2 muỗng canh'},
    ],
    spice: ['Tỏi', 'Ớt', 'Muối'],
    process:
      'Sơ chế thịt gà, nướng thịt, chế biến nước mắm, nấu cơm, chuẩn bị rau sống.',
    perform: 'Đặt cơm và thịt gà trong đĩa, chấm nước mắm trước khi ăn.',
    use: 'Dùng cơm gà khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[0],
  },

  {
    id: 'm4',
    title: 'Gà rang muối',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 2,
    description:
      'Gà rang muối là một món ăn ngon, bao gồm gà chiên và gia vị muối.',
    ingredients: [
      {name: 'Thịt gà', amount: '300g'},
      {name: 'Muối', amount: '1 muỗng canh'},
      {name: 'Tiêu', amount: '1/2 muỗng cà phê'},
      {name: 'Bột ngọt', amount: '1/2 muỗng cà phê'},
    ],
    spice: ['Ớt', 'Hành', 'Tỏi'],
    process: 'Sơ chế thịt gà, chiên gà, rang muối và gia vị.',
    perform: 'Xào gà với muối và gia vị cho đến khi thịt gà vàng đều.',
    use: 'Dùng gà rang muối khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[1],
  },
  {
    id: 'm5',
    title: 'Gà hầm thuốc bắc',
    linkImage: 'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 4,
    description:
      'Gà hầm thuốc bắc là một món ăn truyền thống, bao gồm gà hầm và các loại thuốc bắc.',
    ingredients: [
      {name: 'Thịt gà', amount: '1 con'},
      {name: 'Thuốc bắc', amount: '1 gói'},
      {name: 'Nước dừa', amount: '500ml'},
      {name: 'Hành', amount: '1 củ'},
    ],
    spice: ['Gừng', 'Đường', 'Muối'],
    process: 'Sơ chế thịt gà, hầm gà với thuốc bắc và nước dừa.',
    perform: 'Hầm gà với thuốc bắc và gia vị cho đến khi gà mềm.',
    use: 'Dùng gà hầm thuốc bắc khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[1],
  },
  {
    id: 'm6',
    title: 'Gà xào sả ớt',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 2,
    description:
      'Gà xào sả ớt là một món ăn thơm ngon, bao gồm gà xào và gia vị sả ớt.',
    ingredients: [
      {name: 'Thịt gà', amount: '300g'},
      {name: 'Sả', amount: '2 cây'},
      {name: 'Ớt', amount: '2 quả'},
      {name: 'Hành', amount: '1 củ'},
    ],
    spice: ['Nước mắm', 'Muối', 'Đường'],
    process: 'Sơ chế thịt gà, xào gà với sả và ớt.',
    perform: 'Xào gà với sả và ớt cho đến khi thịt gà chín.',
    use: 'Dùng gà xào sả ớt khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[1],
  },

  {
    id: 'm7',
    title: 'Cá chiên giòn',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 4,
    description:
      'Cá chiên giòn là một món ăn ngon, bao gồm cá chiên và gia vị.',
    ingredients: [
      {name: 'Cá', amount: '500g'},
      {name: 'Bột chiên giòn', amount: '200g'},
      {name: 'Dầu ăn', amount: 'đủ để chiên'},
      {name: 'Muối', amount: '1 muỗng canh'},
    ],
    spice: ['Tiêu', 'Ớt', 'Hành'],
    process: 'Sơ chế cá, chiên cá với bột chiên giòn và gia vị.',
    perform: 'Chiên cá cho đến khi cá vàng giòn.',
    use: 'Dùng cá chiên giòn khi còn nóng.',
    tips: 'Nên chọn cá tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[2],
  },
  {
    id: 'm8',
    title: 'Cá kho tộ',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 4,
    description:
      'Cá kho tộ là một món ăn truyền thống của Việt Nam, bao gồm cá kho tộ được nấu chảy với nước mắm.',
    ingredients: [
      {name: 'Cá', amount: '500g'},
      {name: 'Nước mắm', amount: '3 muỗng canh'},
      {name: 'Đường', amount: '1 muỗng canh'},
      {name: 'Hành lá', amount: '1 củ'},
    ],
    spice: ['Tỏi', 'Ớt', 'Hành'],
    process: 'Sơ chế cá, chế biến nước mắm, nấu cá kho tộ với gia vị.',
    perform: 'Đặt cá kho tộ trong nồi, nấu chảy với nước mắm và gia vị.',
    use: 'Dùng cá kho tộ khi còn nóng.',
    tips: 'Nên chọn cá tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[2],
  },

  {
    id: 'm9',
    title: 'Cá hấp hành gừng',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 2,
    description:
      'Cá hấp hành gừng là một món ăn ngon, bao gồm cá hấp với hành và gừng.',
    ingredients: [
      {name: 'Cá', amount: '500g'},
      {name: 'Hành', amount: '1 củ'},
      {name: 'Gừng', amount: '2 củ'},
      {name: 'Nước mắm', amount: '2 muỗng canh'},
    ],
    spice: ['Tiêu', 'Ớt', 'Muối'],
    process: 'Sơ chế cá, hấp cá với hành, gừng và gia vị.',
    perform: 'Hấp cá với hành, gừng và gia vị cho đến khi cá chín.',
    use: 'Dùng cá hấp hành gừng khi còn nóng.',
    tips: 'Nên chọn cá tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[2],
  },
  {
    id: 'm10',
    title: 'Cá nướng mắm ruốc',
    linkImage: 'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 4,
    description:
      'Cá nướng mắm ruốc là một món ăn thơm ngon, bao gồm cá nướng với mắm ruốc.',
    ingredients: [
      {name: 'Cá', amount: '1 con'},
      {name: 'Mắm ruốc', amount: '100g'},
      {name: 'Ớt', amount: '2 quả'},
      {name: 'Hành', amount: '1 củ'},
    ],
    spice: ['Muối', 'Đường', 'Hành lá'],
    process: 'Sơ chế cá, nướng cá với mắm ruốc và gia vị.',
    perform: 'Nướng cá với mắm ruốc và gia vị cho đến khi cá chín vàng.',
    use: 'Dùng cá nướng mắm ruốc khi còn nóng.',
    tips: 'Nên chọn cá tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[2],
  },
  {
    id: 'm11',
    title: 'Canh chua cá lóc',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 4,
    description:
      'Canh chua cá lóc là một món ăn truyền thống, bao gồm cá lóc hầm trong nước mắm.',
    ingredients: [
      {name: 'Cá lóc', amount: '500g'},
      {name: 'Nước mắm', amount: '3 muỗng canh'},
      {name: 'Dưa chuột', amount: '1 quả'},
      {name: 'Ngò om', amount: '1 bó'},
    ],
    spice: ['Ớt', 'Hành', 'Me'],
    process: 'Sơ chế cá lóc, hầm cá lóc với nước mắm và gia vị.',
    perform:
      'Hầm cá lóc với nước mắm, dưa chuột và gia vị cho đến khi cá chín.',
    use: 'Dùng canh chua cá lóc khi còn nóng.',
    tips: 'Nên chọn cá lóc tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[2],
  },
  {
    id: 'm12',
    title: 'Bánh mì thịt',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 1,
    description:
      'Bánh mì thịt là một món ăn phổ biến, bao gồm bánh mì và thịt.',
    ingredients: [
      {name: 'Bánh mì', amount: '1 ổ'},
      {name: 'Thịt bò', amount: '100g'},
      {name: 'Rau sống', amount: '100g'},
      {name: 'Sốt mayonnaise', amount: '2 muỗng canh'},
    ],
    spice: ['Tiêu', 'Muối', 'Ớt'],
    process: 'Sơ chế thịt bò, nướng thịt, chuẩn bị bánh mì và rau sống.',
    perform: 'Xếp thịt bò, rau sống và sốt mayonnaise trên bánh mì.',
    use: 'Dùng bánh mì thịt khi còn nóng.',
    tips: 'Nên chọn thịt bò tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[3],
  },

  {
    id: 'm13',
    title: 'Bánh mì pate',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 1,
    description:
      'Bánh mì pate là một món ăn phổ biến, bao gồm bánh mì và pate.',
    ingredients: [
      {name: 'Bánh mì', amount: '1 ổ'},
      {name: 'Pate', amount: '50g'},
      {name: 'Dưa chua', amount: '2 quả'},
      {name: 'Ngò gai', amount: '1 bó'},
    ],
    spice: ['Tiêu', 'Muối', 'Ớt'],
    process: 'Chuẩn bị bánh mì, pate, dưa chua và ngò gai.',
    perform: 'Xếp pate, dưa chua và ngò gai trên bánh mì.',
    use: 'Dùng bánh mì pate khi còn nóng.',
    tips: 'Nên chọn pate tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[3],
  },
  {
    id: 'm14',
    title: 'Bánh mì thịt nướng',
    linkImage: 'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 1,
    description:
      'Bánh mì thịt nướng là một món ăn phổ biến, bao gồm bánh mì và thịt nướng.',
    ingredients: [
      {name: 'Bánh mì', amount: '1 ổ'},
      {name: 'Thịt nướng', amount: '100g'},
      {name: 'Rau sống', amount: '100g'},
      {name: 'Sốt mayonnaise', amount: '2 muỗng canh'},
    ],
    spice: ['Tiêu', 'Muối', 'Ớt'],
    process: 'Sơ chế thịt nướng, nướng thịt, chuẩn bị bánh mì và rau sống.',
    perform: 'Xếp thịt nướng, rau sống và sốt mayonnaise trên bánh mì.',
    use: 'Dùng bánh mì thịt nướng khi còn nóng.',
    tips: 'Nên chọn thịt tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[3],
  },

  {
    id: 'm15',
    title: 'Bánh sandwich thịt',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 1,
    description:
      'Bánh sandwich thịt là một món ăn phổ biến cho trẻ em, bao gồm bánh sandwich và thịt.',
    ingredients: [
      {name: 'Bánh sandwich', amount: '1 ổ'},
      {name: 'Thịt bò', amount: '50g'},
      {name: 'Dưa leo', amount: '2 lát'},
      {name: 'Sốt mayonnaise', amount: '2 muỗng canh'},
    ],
    spice: ['Tiêu', 'Muối', 'Ớt'],
    process: 'Chuẩn bị bánh sandwich, thịt bò, dưa leo và sốt mayonnaise.',
    perform: 'Xếp thịt bò, dưa leo và sốt mayonnaise trên bánh sandwich.',
    use: 'Dùng bánh sandwich thịt khi còn nóng.',
    tips: 'Nên chọn thịt bò tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[4],
  },
  {
    id: 'm16',
    title: 'Cháo gà',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 1,
    description:
      'Cháo gà là một món ăn phổ biến cho trẻ em, bao gồm gà và cháo.',
    ingredients: [
      {name: 'Gà', amount: '100g'},
      {name: 'Gạo', amount: '100g'},
      {name: 'Hành lá', amount: '1 củ'},
      {name: 'Gừng', amount: '1 củ'},
    ],
    spice: ['Muối', 'Tiêu', 'Hành'],
    process: 'Sơ chế gà, nấu cháo với gạo và gia vị.',
    perform: 'Trộn gà và cháo, thêm gia vị trước khi ăn.',
    use: 'Dùng cháo gà khi còn nóng.',
    tips: 'Nên chọn gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[4],
  },

  {
    id: 'm17',
    title: 'Mỳ ý thịt bò',
    linkImage: 'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 1,
    description:
      'Mỳ ý thịt bò là một món ăn phổ biến cho trẻ em, bao gồm mỳ ý và thịt bò.',
    ingredients: [
      {name: 'Mỳ ý', amount: '100g'},
      {name: 'Thịt bò', amount: '100g'},
      {name: 'Sốt cà chua', amount: '3 muỗng canh'},
      {name: 'Phô mai', amount: '2 lát'},
    ],
    spice: ['Muối', 'Tiêu', 'Ớt'],
    process: 'Chuẩn bị mỳ ý, thịt bò, sốt cà chua và phô mai.',
    perform:
      'Luộc mỳ ý, chiên thịt bò, trộn mỳ ý và sốt cà chua, trang trí với phô mai.',
    use: 'Dùng mỳ ý thịt bò khi còn nóng.',
    tips: 'Nên chọn thịt bò tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[4],
  },
  {
    id: 'm18',
    title: 'Cơm rang gà',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 1,
    description:
      'Cơm rang gà là một món ăn phổ biến cho trẻ em, bao gồm cơm và gà rang.',
    ingredients: [
      {name: 'Cơm', amount: '200g'},
      {name: 'Gà', amount: '100g'},
      {name: 'Hành lá', amount: '1 củ'},
      {name: 'Trứng', amount: '1 quả'},
    ],
    spice: ['Muối', 'Đường', 'Hành'],
    process: 'Sơ chế gà, rang gà với cơm và gia vị.',
    perform: 'Rang gà với cơm và gia vị cho đến khi cơm và gà chín.',
    use: 'Dùng cơm rang gà khi còn nóng.',
    tips: 'Nên chọn gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[4],
  },

  {
    id: 'm19',
    title: 'Súp lơ xanh',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 1,
    description:
      'Súp lơ xanh là một món ăn phổ biến cho người mẹ, bao gồm lơ xanh và nước lọc.',
    ingredients: [
      {name: 'Lơ xanh', amount: '1 trái'},
      {name: 'Nước lọc', amount: '500ml'},
      {name: 'Hành', amount: '1 củ'},
      {name: 'Gừng', amount: '1 củ'},
    ],
    spice: ['Muối', 'Tiêu', 'Hành lá'],
    process: 'Sơ chế lơ xanh, luộc lơ xanh với nước lọc và gia vị.',
    perform: 'Luộc lơ xanh với nước lọc và gia vị cho đến khi lơ mềm.',
    use: 'Dùng súp lơ xanh khi còn nóng.',
    tips: 'Nên chọn lơ xanh tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[5],
  },
  {
    id: 'm20',
    title: 'Salad trứng',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 1,
    description:
      'Salad trứng là một món ăn phổ biến cho người mẹ, bao gồm trứng và rau sống.',
    ingredients: [
      {name: 'Trứng', amount: '2 quả'},
      {name: 'Rau sống', amount: '200g'},
      {name: 'Dầu olive', amount: '2 muỗng canh'},
      {name: 'Giấm', amount: '1 muỗng canh'},
    ],
    spice: ['Muối', 'Tiêu', 'Ớt'],
    process: 'Luộc trứng, chuẩn bị rau sống và gia vị.',
    perform:
      'Trộn trứng, rau sống, dầu olive, giấm và gia vị để tạo thành salad.',
    use: 'Dùng salad trứng khi còn tươi.',
    tips: 'Nên chọn trứng tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[5],
  },
  {
    id: 'm21',
    title: 'Canh chua tôm',
    linkImage: 'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 1,
    description:
      'Canh chua tôm là một món ăn phổ biến cho người mẹ, bao gồm tôm và nước lọc.',
    ingredients: [
      {name: 'Tôm', amount: '200g'},
      {name: 'Nước lọc', amount: '500ml'},
      {name: 'Dưa chuột', amount: '1 quả'},
      {name: 'Ngò om', amount: '1 bó'},
    ],
    spice: ['Ớt', 'Hành', 'Me'],
    process: 'Sơ chế tôm, hầm tôm với nước lọc và gia vị.',
    perform: 'Hầm tôm với nước lọc, dưa chuột và gia vị cho đến khi tôm chín.',
    use: 'Dùng canh chua tôm khi còn nóng.',
    tips: 'Nên chọn tôm tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[5],
  },
  {
    id: 'm22',
    title: 'Thịt kho trứng',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 2,
    description:
      'Thịt kho trứng là một món ăn khoái khẩu, bao gồm thịt và trứng.',
    ingredients: [
      {name: 'Thịt heo', amount: '200g'},
      {name: 'Trứng', amount: '4 quả'},
      {name: 'Nước mắm', amount: '2 muỗng canh'},
      {name: 'Đường', amount: '1 muỗng canh'},
    ],
    spice: ['Hành', 'Tỏi', 'Tiêu'],
    process: 'Sơ chế thịt heo, kho thịt với trứng và gia vị.',
    perform:
      'Kho thịt heo với trứng, nước mắm, đường và gia vị cho đến khi thịt mềm.',
    use: 'Dùng thịt kho trứng khi còn nóng.',
    tips: 'Nên chọn thịt heo tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[6],
  },
  {
    id: 'm23',
    title: 'Cá kho tộ',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 4,
    description:
      'Cá kho tộ là một món ăn truyền thống, bao gồm cá kho tộ được nấu chảy với nước mắm.',
    ingredients: [
      {name: 'Cá', amount: '500g'},
      {name: 'Nước mắm', amount: '3 muỗng canh'},
      {name: 'Đường', amount: '1 muỗng canh'},
      {name: 'Hành lá', amount: '1 củ'},
    ],
    spice: ['Tỏi', 'Ớt', 'Hành'],
    process: 'Sơ chế cá, chế biến nước mắm, nấu cá kho tộ với gia vị.',
    perform: 'Đặt cá kho tộ trong nồi, nấu chảy với nước mắm và gia vị.',
    use: 'Dùng cá kho tộ khi còn nóng.',
    tips: 'Nên chọn cá tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[6],
  },
  {
    id: 'm24',
    title: 'Thịt kho tàu',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 2,
    description:
      'Thịt kho tàu là một món ăn truyền thống, bao gồm thịt kho với nước mắm và các gia vị.',
    ingredients: [
      {name: 'Thịt heo', amount: '300g'},
      {name: 'Nước mắm', amount: '3 muỗng canh'},
      {name: 'Đường', amount: '1 muỗng canh'},
      {name: 'Hành', amount: '1 củ'},
    ],
    spice: ['Tỏi', 'Ớt', 'Hành lá'],
    process: 'Sơ chế thịt heo, kho thịt với nước mắm và gia vị.',
    perform: 'Kho thịt heo với nước mắm, đường và gia vị cho đến khi thịt mềm.',
    use: 'Dùng thịt kho tàu khi còn nóng.',
    tips: 'Nên chọn thịt heo tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[6],
  },
  {
    id: 'm25',
    title: 'Cá kho riềng',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 4,
    description:
      'Cá kho riềng là một món ăn ngon, bao gồm cá kho với nước mắm và riềng.',
    ingredients: [
      {name: 'Cá', amount: '500g'},
      {name: 'Nước mắm', amount: '3 muỗng canh'},
      {name: 'Đường', amount: '1 muỗng canh'},
      {name: 'Riềng', amount: '30g'},
    ],
    spice: ['Tỏi', 'Ớt', 'Hành'],
    process: 'Sơ chế cá, chế biến nước mắm, nấu cá kho với riềng và gia vị.',
    perform:
      'Đặt cá kho riềng trong nồi, nấu chảy với nước mắm, đường, riềng và gia vị.',
    use: 'Dùng cá kho riềng khi còn nóng.',
    tips: 'Nên chọn cá tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[6],
  },
  // Thịt gà
  {
    id: 'm26',
    title: 'Gà nướng mật ong',
    linkImage: 'https://giadinh.mediacdn.vn/zoom/740_463/2017/bun-1498639285275.jpg',
    forPeople: 2,
    description:
      'Gà nướng mật ong là một món ăn ngon, bao gồm gà nướng với mật ong và các gia vị.',
    ingredients: [
      {name: 'Thịt gà', amount: '500g'},
      {name: 'Mật ong', amount: '3 muỗng canh'},
      {name: 'Nước mắm', amount: '2 muỗng canh'},
      {name: 'Tương ớt', amount: '1 muỗng canh'},
    ],
    spice: ['Hành', 'Tỏi', 'Ớt'],
    process: 'Sơ chế thịt gà, trộn mật ong, nước mắm, tương ớt và gia vị.',
    perform:
      'Ướp gà với hỗn hợp mật ong và gia vị, nướng gà cho đến khi chín vàng.',
    use: 'Dùng gà nướng mật ong khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[7],
  },
  {
    id: 'm27',
    title: 'Gà kho gừng',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 2,
    description:
      'Gà kho gừng là một món ăn ngon, bao gồm gà kho với gừng và các gia vị.',
    ingredients: [
      {name: 'Thịt gà', amount: '500g'},
      {name: 'Gừng', amount: '30g'},
      {name: 'Nước mắm', amount: '2 muỗng canh'},
      {name: 'Đường', amount: '1 muỗng canh'},
    ],
    spice: ['Tỏi', 'Ớt', 'Hành'],
    process: 'Sơ chế thịt gà, kho thịt với gừng, nước mắm, đường và gia vị.',
    perform:
      'Kho thịt gà với gừng, nước mắm, đường và gia vị cho đến khi thịt mềm.',
    use: 'Dùng gà kho gừng khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[7],
  },
  {
    id: 'm28',
    title: 'Gà chiên nước mắm',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 2,
    description:
      'Gà chiên nước mắm là một món ăn ngon, bao gồm gà chiên với nước mắm và các gia vị.',
    ingredients: [
      {name: 'Thịt gà', amount: '500g'},
      {name: 'Nước mắm', amount: '3 muỗng canh'},
      {name: 'Hành lá', amount: '1 củ'},
      {name: 'Ớt', amount: '2 quả'},
    ],
    spice: ['Hành', 'Tỏi', 'Tiêu'],
    process: 'Sơ chế thịt gà, chiên gà với nước mắm và gia vị.',
    perform:
      'Chiên gà với nước mắm, hành lá, ớt và gia vị cho đến khi gà chín vàng.',
    use: 'Dùng gà chiên nước mắm khi còn nóng.',
    tips: 'Nên chọn thịt gà tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[7],
  },
  // Tăng năng lượng
  {
    id: 'm29',
    title: 'Cơm cuộn thịt',
    linkImage: 'https://cdn.tgdd.vn/2021/04/CookProduct/1-1200x676-21.jpg',
    forPeople: 1,
    description:
      'Cơm cuộn thịt là một món ăn tăng năng lượng, bao gồm cơm và thịt.',
    ingredients: [
      {name: 'Cơm', amount: '200g'},
      {name: 'Thịt bò', amount: '100g'},
      {name: 'Rau sống', amount: '100g'},
      {name: 'Sốt xì dầu', amount: '2 muỗng canh'},
    ],
    spice: ['Muối', 'Tiêu', 'Ớt'],
    process: 'Nấu cơm, sơ chế thịt bò, chuẩn bị rau sống và sốt xì dầu.',
    perform: 'Xếp cơm, thịt bò, rau sống và sốt xì dầu trên cơm, cuộn lại.',
    use: 'Dùng cơm cuộn thịt khi còn nóng.',
    tips: 'Nên chọn thịt bò tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[8],
  },
  {
    id: 'm30',
    title: 'Bánh mì xúc xích',
    linkImage: 'https://i.ytimg.com/vi/0UqV5a9XIho/maxresdefault.jpg',
    forPeople: 1,
    description:
      'Bánh mì xúc xích là một món ăn tăng năng lượng, bao gồm bánh mì và xúc xích.',
    ingredients: [
      {name: 'Bánh mì', amount: '1 ổ'},
      {name: 'Xúc xích', amount: '2 cây'},
      {name: 'Dưa chua', amount: '2 lát'},
      {name: 'Sốt mayonnaise', amount: '2 muỗng canh'},
    ],
    spice: ['Tiêu', 'Muối', 'Ớt'],
    process: 'Sơ chế xúc xích, nướng xúc xích, chuẩn bị bánh mì và dưa chua.',
    perform: 'Xếp xúc xích, dưa chua và sốt mayonnaise trên bánh mì.',
    use: 'Dùng bánh mì xúc xích khi còn nóng.',
    tips: 'Nên chọn xúc xích tươi mới để có hương vị ngon nhất.',
    category: CATEGORIES[8],
  },
];
